// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaML4iL1Jp9oiS0_p8rnTQWHExV06yq_o',
    appId: '1:365523796398:web:d4b0a2c227c5e356ff883f',
    messagingSenderId: '365523796398',
    projectId: 'splitsync-91f14',
    authDomain: 'splitsync-91f14.firebaseapp.com',
    databaseURL: 'https://splitsync-91f14-default-rtdb.firebaseio.com',
    storageBucket: 'splitsync-91f14.appspot.com',
    measurementId: 'G-L4WEJJQ8CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEfEzOPcz42L8ynU8HNL6eYMe8Y8zbDcs',
    appId: '1:365523796398:android:1880d172323edf32ff883f',
    messagingSenderId: '365523796398',
    projectId: 'splitsync-91f14',
    databaseURL: 'https://splitsync-91f14-default-rtdb.firebaseio.com',
    storageBucket: 'splitsync-91f14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYhFxcmVkw3SZly4y3sof-e9Qf9NKa5ik',
    appId: '1:365523796398:ios:b1045553c14403ddff883f',
    messagingSenderId: '365523796398',
    projectId: 'splitsync-91f14',
    databaseURL: 'https://splitsync-91f14-default-rtdb.firebaseio.com',
    storageBucket: 'splitsync-91f14.appspot.com',
    iosBundleId: 'com.example.splitsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYhFxcmVkw3SZly4y3sof-e9Qf9NKa5ik',
    appId: '1:365523796398:ios:e655f65f192a4c66ff883f',
    messagingSenderId: '365523796398',
    projectId: 'splitsync-91f14',
    databaseURL: 'https://splitsync-91f14-default-rtdb.firebaseio.com',
    storageBucket: 'splitsync-91f14.appspot.com',
    iosBundleId: 'com.example.splitsync.RunnerTests',
  );
}
